cache:
  paths:
    - vendor

stages:
  - test

services:
  - mysql:5.7
  - postgres:13.13

before_script:
  - apt-get update
  - apt-get install gcc -y
  - gem update --system 3.4.22
  - gem install bundler:2.4.22 --no-doc
  - bundle install --jobs=2 --retry=3
  - bundle exec appraisal clean
  - bundle exec appraisal generate

variables:
  # Configure mysql environment variables (https://hub.docker.com/_/mysql/)
  MYSQL_DATABASE: spectacles_test
  MYSQL_ROOT_PASSWORD: rootpassword
  MYSQL_PASSWORD: password
  MYSQL_USER: runner
  MYSQL_HOST: mysql
  POSTGRES_DB: "postgres"
  POSTGRES_USER: runner
  POSTGRES_HOST: postgres
  POSTGRES_HOST_AUTH_METHOD: "trust"
  POSTGRES_PASSWORD: ""

specs:
  stage: test
  image: "${IMAGE_NAME}"
  script:
    - bundle exec appraisal $GEMFILE_NAME bundle install --jobs=2 --retry=3
    - bundle exec appraisal $GEMFILE_NAME bundle exec rake rubocop
    - bundle exec appraisal $GEMFILE_NAME bundle exec rspec
  parallel:
    matrix:
      - IMAGE_NAME: ["ruby:2.7", "jruby:9.3-jdk"]
        GEMFILE_NAME: [rails-42, rails-52, rails-61]
      - IMAGE_NAME: ["ruby:3.0", "ruby:3.1", "jruby:9.3-jdk17"]
        GEMFILE_NAME: [rails-61]
